# Site settings
# in the templates available like {{ site.myvariable }}.
title: 서동욱 개발일지
email: sdwtony@kakao.com
brand: 서동욱
headline: Firmware Developer
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://donguk-tony.github.io/" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: sdwtony@kakao.com
phone: +82-9248-2786

# Tracking
googleAnalitycsID: UA-83933844-1

